### ISSUE TITLE
Sync version in tags and package.json

### ISSUE THREAD

**Issue by eirnym** [poseidon/wait-for-status-checks#204]
At the time version in [package.json](https://github.com/poseidon/wait-for-status-checks/blob/c19833a1c2fe85469fa1842c4390d47951be9bd3/package.json) shows `0.3.0`, while actual version in GitHub releases is `0.4.1`. Could you please sync these versions in next release?

**Comment by dghubble** [comment]
Does this break something of yours?

**Comment by eirnym** [comment]
nope, but it would be nice if this would be handled by a `release` workflow

**Comment by dghubble** [comment]
The version matches in v0.5.0
