### ISSUE TITLE
doesn't verify all checks

### ISSUE THREAD

**Issue by OneCyrus** [poseidon/wait-for-status-checks#8]
looks like this action only verifies the first 30 checks which are returned by default. Currently we have about 120 checks in a monorepo (most checks are skipped) so the action succeeds even when other checks are still running.

![image](https://github.com/poseidon/wait-for-status-checks/assets/7747800/6545b7c2-e19a-4edb-af8d-9d99fda425b6)

https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-runs-for-a-git-reference

**Comment by dghubble** [comment]
Wanna make a PR? I'm not likely to fix it unless it affects my use cases which are smaller

**Comment by dghubble** [comment]
In v0.2.0, it gets up to 100 check runs

**Comment by OneCyrus** [comment]
with PR #12 we fetch additional pages when not all are retrieved in the first request

**Comment by nategoethel** [comment]
This issue seems to be coming back intermittently? Sometimes I see all runs picked up, sometimes I only see a couple, even though more have been triggered. Any ideas here?
